server:
  port: 8080

logging:
  level:
    root: info
    cn.edu.zucc.crabxyj.springbootshiro.dao: debug

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/normal?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# ====================MybatisPlus====================
mybatis-plus:
  type-aliases-package: cn.edu.zucc.crabxyj.springbootshiro.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:/mapper/*Mapper.xml
